### ISSUE TITLE
getCookies broken on most of devtools versions 

### ISSUE THREAD

**Issue by pmlhotra** [sandipchitale/DevToolsApp#1]
The versions of devtools in this application do not show any cookies while remotely debugging chrome on android.

![screen shot 2015-06-05 at 12 12 21 pm](https://cloud.githubusercontent.com/assets/4486964/8000934/3c17f30c-0b7e-11e5-8baa-63cf70f6b661.png)

Also tried to debug it by deploying  a local version of chrome devtools, on clicking the cookie I get `Network.getCookie not found` errors in console like this:

```
1. Request with id = 268 failed. {"code":-32601,"message":"'Network.getCookies' wasn't found"}
InspectorBackendClass.AgentPrototype.dispatchResponse   @   InspectorBackend.js:965
InspectorBackendClass.Connection.dispatch   @   InspectorBackend.js:482
InspectorBackendClass.WebSocketConnection._onMessage    @   InspectorBackend.js:694

2. 'Network.getCookies' wasn't found
mycallback  @   CookieParser.js:401
CallbackBarrier._incomingCallback   @   utilities.js:1448
InspectorBackendClass.AgentPrototype.dispatchResponse   @   InspectorBackend.js:985
InspectorBackendClass.Connection.dispatch   @   InspectorBackend.js:482
InspectorBackendClass.WebSocketConnection._onMessage
```

I used https://medium.com/@aslushnikov/hacking-chrome-devtools-8c8896f5cef3 to deploy a local copy of devtools.

Also found something relevant here https://code.google.com/p/chromium/issues/detail?id=476389
Any ideas on how to make it work ? TIA !

This work for remotely debugging a desktop chrome but doesn't work for chrome for android.
/cc @sandipchitale  @paulirish  @auchenberg

**Comment by pmlhotra** [comment]
Looks like a problem with latest version of devtools, older ones work fine. I'll report an issue with them. This project works fine. Thanks.

**Comment by auchenberg** [comment]
This seems to be due to a protocol change of the `Network.Cookie` object, which I stumped upon in Pauls update of the docs:
https://github.com/ChromeDevTools/debugger-protocol-viewer/commit/d807582d29776b3d7f5a089d7bd1aee08f0e1402
